[functions.tiflis-auth-migrate]
verify_jwt = false

[functions.tiflis-secure-api]
verify_jwt = true

[functions.tiflis-menu-api]
verify_jwt = true

[functions.tiflis-reserve-api]
verify_jwt = true

[functions.tiflis-staff-api]
verify_jwt = true
