begin;

create table if not exists public.ops_duty_plan_assignments (
  id bigint generated by default as identity primary key,
  plan_type text not null check (plan_type in ('daily','handover')),
  work_date date not null,
  duty_key text not null check (char_length(duty_key) between 2 and 80),
  assignee_id text not null references public.users(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending','done')),
  completed_by text,
  completed_at timestamptz,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_type, work_date, duty_key)
);

create table if not exists public.ops_zone_plan_assignments (
  id bigint generated by default as identity primary key,
  work_date date not null,
  zone_key text not null check (char_length(zone_key) between 2 and 80),
  slot smallint not null check (slot between 1 and 3),
  assignee_id text not null references public.users(id) on delete restrict,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (work_date, zone_key, slot),
  unique (work_date, zone_key, assignee_id)
);

create table if not exists public.ops_plan_publications (
  plan_type text not null check (plan_type in ('daily','handover')),
  work_date date not null,
  published_by text,
  published_at timestamptz not null default now(),
  telegram_sent integer not null default 0 check (telegram_sent >= 0),
  telegram_skipped integer not null default 0 check (telegram_skipped >= 0),
  primary key (plan_type, work_date)
);

create index if not exists ops_duty_plan_date_assignee_idx
  on public.ops_duty_plan_assignments (work_date, assignee_id, plan_type, status);
create index if not exists ops_zone_plan_date_assignee_idx
  on public.ops_zone_plan_assignments (work_date, assignee_id, zone_key);
create index if not exists ops_plan_publications_date_idx
  on public.ops_plan_publications (work_date desc, plan_type);

drop trigger if exists ops_duty_plan_assignments_set_updated_at on public.ops_duty_plan_assignments;
create trigger ops_duty_plan_assignments_set_updated_at
before update on public.ops_duty_plan_assignments
for each row execute function public.set_updated_at();

drop trigger if exists ops_zone_plan_assignments_set_updated_at on public.ops_zone_plan_assignments;
create trigger ops_zone_plan_assignments_set_updated_at
before update on public.ops_zone_plan_assignments
for each row execute function public.set_updated_at();

create or replace function public.replace_ops_duty_plan(
  p_plan_type text,
  p_work_date date,
  p_assignments jsonb,
  p_zones jsonb,
  p_actor text
)
returns table (duty_count integer, zone_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_duty_count integer := 0;
  v_zone_count integer := 0;
begin
  if p_plan_type not in ('daily','handover') then
    raise exception 'invalid plan type';
  end if;
  if p_work_date is null then
    raise exception 'invalid work date';
  end if;
  if jsonb_typeof(coalesce(p_assignments, '[]'::jsonb)) <> 'array' then
    raise exception 'assignments must be an array';
  end if;
  if jsonb_typeof(coalesce(p_zones, '[]'::jsonb)) <> 'array' then
    raise exception 'zones must be an array';
  end if;

  delete from public.ops_duty_plan_assignments
  where plan_type = p_plan_type and work_date = p_work_date;

  insert into public.ops_duty_plan_assignments (
    plan_type, work_date, duty_key, assignee_id, created_by
  )
  select
    p_plan_type,
    p_work_date,
    trim(item.duty_key),
    trim(item.assignee_id),
    p_actor
  from jsonb_to_recordset(coalesce(p_assignments, '[]'::jsonb))
    as item(duty_key text, assignee_id text)
  where nullif(trim(item.duty_key), '') is not null
    and nullif(trim(item.assignee_id), '') is not null;
  get diagnostics v_duty_count = row_count;

  if p_plan_type = 'daily' then
    delete from public.ops_zone_plan_assignments where work_date = p_work_date;

    insert into public.ops_zone_plan_assignments (
      work_date, zone_key, slot, assignee_id, created_by
    )
    select
      p_work_date,
      trim(item.zone_key),
      item.slot,
      trim(item.assignee_id),
      p_actor
    from jsonb_to_recordset(coalesce(p_zones, '[]'::jsonb))
      as item(zone_key text, slot smallint, assignee_id text)
    where nullif(trim(item.zone_key), '') is not null
      and item.slot between 1 and 3
      and nullif(trim(item.assignee_id), '') is not null;
    get diagnostics v_zone_count = row_count;
  end if;

  delete from public.ops_plan_publications
  where plan_type = p_plan_type and work_date = p_work_date;

  return query select v_duty_count, v_zone_count;
end;
$$;

revoke all on function public.replace_ops_duty_plan(text, date, jsonb, jsonb, text) from public;
revoke execute on function public.replace_ops_duty_plan(text, date, jsonb, jsonb, text) from anon, authenticated;
grant execute on function public.replace_ops_duty_plan(text, date, jsonb, jsonb, text) to service_role;

alter table public.ops_duty_plan_assignments enable row level security;
alter table public.ops_zone_plan_assignments enable row level security;
alter table public.ops_plan_publications enable row level security;

revoke all on table public.ops_duty_plan_assignments from anon, authenticated;
revoke all on table public.ops_zone_plan_assignments from anon, authenticated;
revoke all on table public.ops_plan_publications from anon, authenticated;
grant all on table public.ops_duty_plan_assignments to service_role;
grant all on table public.ops_zone_plan_assignments to service_role;
grant all on table public.ops_plan_publications to service_role;
grant usage, select on sequence public.ops_duty_plan_assignments_id_seq to service_role;
grant usage, select on sequence public.ops_zone_plan_assignments_id_seq to service_role;

commit;
