begin;

-- Standalone team birthday roster for the "Персонал → День народження" tab.
-- Deliberately independent from public.users/staff_profiles: most people on
-- this roster have no portal account (never logged in, or never will), so
-- this table must not require an auth link to exist.

create table if not exists public.staff_birthdays (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(trim(full_name)) between 1 and 120),
  position text not null check (position in (
    'admin', 'bartender', 'waiter', 'hostess', 'runner', 'sommelier',
    'head_chef', 'cook', 'cook_assistant', 'housekeeping', 'facilities',
    'hearth_keeper', 'purchasing'
  )),
  position_detail text check (
    (position = 'cook' and position_detail in ('hot', 'cold', 'pastry', 'grill'))
    or (position = 'housekeeping' and position_detail in ('cleaner', 'wash_white', 'wash_black'))
    or (position not in ('cook', 'housekeeping') and position_detail is null)
  ),
  position2 text check (position2 is null or position2 in (
    'admin', 'bartender', 'waiter', 'hostess', 'runner', 'sommelier',
    'head_chef', 'cook', 'cook_assistant', 'housekeeping', 'facilities',
    'hearth_keeper', 'purchasing'
  )),
  position2_detail text check (
    (position2 = 'cook' and position2_detail in ('hot', 'cold', 'pastry', 'grill'))
    or (position2 = 'housekeeping' and position2_detail in ('cleaner', 'wash_white', 'wash_black'))
    or (
      (position2 is null or position2 not in ('cook', 'housekeeping'))
      and position2_detail is null
    )
  ),
  birthday_month smallint check (birthday_month between 1 and 12),
  birthday_day smallint check (birthday_day between 1 and 31),
  avatar text,
  updated_by text references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((birthday_month is null) = (birthday_day is null)),
  check (position2 is distinct from position)
);

comment on table public.staff_birthdays is
  'Whole-team birthday roster shown on the Персонал → День народження tab. Entries may have no linked users row — most staff here never get portal accounts.';

drop trigger if exists staff_birthdays_set_updated_at on public.staff_birthdays;
create trigger staff_birthdays_set_updated_at
before update on public.staff_birthdays
for each row execute function public.set_updated_at();

alter table public.staff_birthdays enable row level security;

revoke all on table public.staff_birthdays from public, anon, authenticated;
revoke all on sequence public.staff_birthdays_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.staff_birthdays to service_role;
grant usage, select on sequence public.staff_birthdays_id_seq to service_role;

-- Seed with the current team roster. birthday_month/day are day-of-year only
-- (no year captured, matching how the list was provided); entries with no
-- known date are left null and shown as "не вказано" in the UI.
insert into public.staff_birthdays
  (full_name, position, position_detail, position2, position2_detail, birthday_month, birthday_day)
values
  ('Григоренко Юлія', 'admin', null, null, null, 12, 12),
  ('Ковтун Юлія', 'admin', null, null, null, 12, 15),
  ('Гопко Владислав', 'bartender', null, null, null, 5, 19),
  ('Яна', 'bartender', null, null, null, 4, 9),
  ('Бєнуні Арман', 'sommelier', null, 'waiter', null, 11, 26),
  ('Оксана Шиманська', 'hostess', null, null, null, 2, 10),
  ('Аня', 'hostess', null, null, null, 1, 14),
  ('Андрій Швець', 'waiter', null, 'bartender', null, 12, 13),
  ('Княгніцька Оксана', 'waiter', null, null, null, 2, 5),
  ('Опанасенко Дмитро', 'waiter', null, null, null, 1, 23),
  ('Іра', 'waiter', null, null, null, 10, 1),
  ('Каріна Грицуник', 'waiter', null, null, null, 4, 4),
  ('Ліза Кравчишина', 'waiter', null, null, null, 4, 18),
  ('Дмитро Лякін', 'waiter', null, null, null, 5, 22),
  ('Віоріка', 'waiter', null, null, null, 1, 19),
  ('Артем', 'waiter', null, null, null, 5, 13),
  ('Вова', 'runner', null, null, null, 6, 26),
  ('Аліна', 'runner', null, null, null, 5, 15),
  ('Ліза', 'runner', null, null, null, 6, 2),
  ('Рикало Станіслав', 'head_chef', null, null, null, 5, 28),
  ('Адамюк Надія Артурівна', 'cook', null, null, null, 7, 9),
  ('Адамюк Андрій', 'cook', null, null, null, 11, 23),
  ('Вова', 'cook', null, null, null, 7, 26),
  ('Грозний Володимир', 'cook', null, null, null, null, null),
  ('Влад', 'cook', null, null, null, 2, 7),
  ('Мирослава', 'cook', null, null, null, 6, 1),
  ('Іра Школяренко', 'cook', null, null, null, 12, 21),
  ('Інна', 'cook', null, null, null, 12, 26),
  ('Маша', 'cook', null, null, null, 8, 18),
  ('Міша', 'cook', 'grill', null, null, 7, 18),
  ('Діма', 'cook', 'grill', null, null, 3, 26),
  ('Саша', 'cook_assistant', null, null, null, 3, 7),
  ('Тимур', 'cook', null, null, null, 2, 24),
  ('Андрій', 'cook_assistant', null, null, null, 1, 28),
  ('Валерія', 'cook_assistant', null, null, null, 3, 22),
  ('Віка Адамюк', 'cook_assistant', null, null, null, 5, 8),
  ('Віта Ковтун', 'housekeeping', 'wash_black', null, null, null, null),
  ('Валя Саприго', 'housekeeping', 'wash_black', null, null, 11, 27),
  ('Таня', 'housekeeping', 'wash_black', null, null, 5, 3),
  ('Лєна', 'housekeeping', 'wash_black', null, null, null, null),
  ('Мякуш Галина', 'housekeeping', 'cleaner', null, null, null, null),
  ('Анна', 'housekeeping', 'cleaner', null, null, 11, 24),
  ('Марина Герцун', 'housekeeping', 'cleaner', null, null, null, null),
  ('Марина', 'housekeeping', 'cleaner', null, null, 9, 17),
  ('Валя', 'housekeeping', 'cleaner', null, null, null, null),
  ('Ольга', 'housekeeping', 'cleaner', null, null, 6, 8),
  ('Ігор', 'hearth_keeper', null, null, null, 5, 2),
  ('Наташа', 'purchasing', null, null, null, null, null);

commit;
