begin;

create table if not exists public.ops_task_templates (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text not null default 'service'
    check (category in ('opening','service','closing','handover')),
  role_scope text[] not null default array[]::text[],
  shift_codes text[] not null default array[]::text[],
  sort_order integer not null default 0,
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ops_task_assignments (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.ops_task_templates(id) on delete cascade,
  work_date date not null,
  assignee_id text not null references public.users(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending','done','skipped')),
  note text,
  completed_by text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (template_id, work_date, assignee_id)
);

create table if not exists public.ops_handover_notes (
  id bigint generated by default as identity primary key,
  work_date date not null,
  author_id text references public.users(id) on delete set null,
  author_name text not null,
  title text not null,
  body text not null,
  priority text not null default 'medium'
    check (priority in ('low','medium','high','critical')),
  role_scope text[] not null default array[]::text[],
  pinned boolean not null default false,
  resolved_at timestamptz,
  resolved_by text,
  created_at timestamptz not null default now()
);

create index if not exists ops_assignments_user_date_idx
  on public.ops_task_assignments (assignee_id, work_date, status);
create index if not exists ops_handover_date_idx
  on public.ops_handover_notes (work_date desc, pinned desc, created_at desc);
create index if not exists ops_templates_active_idx
  on public.ops_task_templates (active, category, sort_order);

insert into public.ops_task_templates (
  title, description, category, role_scope, sort_order, created_by
)
values
  (
    'Перевірити актуальний стоп-лист',
    'Переконайтесь, що недоступні позиції відображаються в меню до початку активного сервісу.',
    'opening',
    array['admin','chef','cook','waiter','bar','hostess'],
    10,
    'System migration'
  ),
  (
    'Звірити резерви та особливі побажання',
    'Перегляньте гостей, об’єднані столи, попереднє меню та службові примітки на поточну дату.',
    'opening',
    array['admin','waiter','hostess'],
    20,
    'System migration'
  ),
  (
    'Передати незавершені питання наступній зміні',
    'Додайте коротку нотатку, якщо лишились резерви, стоп-позиції, технічні або сервісні питання.',
    'handover',
    array[]::text[],
    100,
    'System migration'
  )
on conflict do nothing;

alter table public.ops_task_templates enable row level security;
alter table public.ops_task_assignments enable row level security;
alter table public.ops_handover_notes enable row level security;

revoke all on table public.ops_task_templates from anon, authenticated;
revoke all on table public.ops_task_assignments from anon, authenticated;
revoke all on table public.ops_handover_notes from anon, authenticated;
grant all on table public.ops_task_templates to service_role;
grant all on table public.ops_task_assignments to service_role;
grant all on table public.ops_handover_notes to service_role;
grant usage, select on sequence public.ops_task_templates_id_seq to service_role;
grant usage, select on sequence public.ops_task_assignments_id_seq to service_role;
grant usage, select on sequence public.ops_handover_notes_id_seq to service_role;

drop trigger if exists ops_task_templates_set_updated_at on public.ops_task_templates;
create trigger ops_task_templates_set_updated_at
before update on public.ops_task_templates
for each row execute function public.set_updated_at();

drop trigger if exists ops_task_assignments_set_updated_at on public.ops_task_assignments;
create trigger ops_task_assignments_set_updated_at
before update on public.ops_task_assignments
for each row execute function public.set_updated_at();

commit;
