begin;

create table if not exists public.portal_config (
  id boolean primary key default true check (id),
  portal_name text not null default 'Тифліс',
  maintenance_mode boolean not null default false,
  announcement_enabled boolean not null default false,
  announcement_title text,
  announcement_body text,
  announcement_priority text not null default 'medium'
    check (announcement_priority in ('low','medium','high','critical')),
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id text,
  actor_name text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx
  on public.audit_log (created_at desc);
create index if not exists audit_log_actor_idx
  on public.audit_log (actor_id, created_at desc);
create index if not exists audit_log_entity_idx
  on public.audit_log (entity_type, entity_id, created_at desc);

insert into public.portal_config (id)
values (true)
on conflict (id) do nothing;

insert into public.audit_log (
  actor_name,
  action,
  entity_type,
  summary,
  metadata
)
select
  'System',
  'admin_control_center_initialized',
  'system',
  'Створено нормалізований адміністративний центр Tiflis v2',
  jsonb_build_object('migration', '20260805_admin_control_center')
where not exists (
  select 1
  from public.audit_log
  where action = 'admin_control_center_initialized'
);

alter table public.portal_config enable row level security;
alter table public.audit_log enable row level security;

revoke all on table public.portal_config from anon, authenticated;
revoke all on table public.audit_log from anon, authenticated;
grant all on table public.portal_config to service_role;
grant all on table public.audit_log to service_role;
grant usage, select on sequence public.audit_log_id_seq to service_role;

drop trigger if exists portal_config_set_updated_at on public.portal_config;
create trigger portal_config_set_updated_at
before update on public.portal_config
for each row execute function public.set_updated_at();

commit;
