begin;

create table if not exists public.staff_records (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  category text not null
    check (category in ('largest_tip', 'plates_at_once', 'tables_at_once')),
  value numeric(12,2) not null check (value > 0),
  achieved_on date not null,
  updated_by text references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, category),
  check (
    (category = 'largest_tip' and value <= 1000000)
    or (
      category in ('plates_at_once', 'tables_at_once')
      and value = trunc(value)
      and value <= 200
    )
  )
);

comment on table public.staff_records is
  'Waiter-entered personal bests. Cash and shift records remain derived from canonical cash and schedule rows.';
comment on column public.staff_records.achieved_on is
  'The date on which the waiter says the manually entered record was achieved.';

drop trigger if exists staff_records_set_updated_at on public.staff_records;
create trigger staff_records_set_updated_at
before update on public.staff_records
for each row execute function public.set_updated_at();

alter table public.staff_records enable row level security;

revoke all on table public.staff_records from public, anon, authenticated;
revoke all on sequence public.staff_records_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.staff_records to service_role;
grant usage, select on sequence public.staff_records_id_seq to service_role;

commit;
