begin;

create table if not exists public.reserve_halls (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reserve_tables (
  id bigint generated by default as identity primary key,
  hall_id bigint not null references public.reserve_halls(id) on delete cascade,
  label text not null,
  capacity smallint not null default 4 check (capacity between 1 and 100),
  kind text not null default 'small',
  position_x numeric(8,3),
  position_y numeric(8,3),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hall_id, label)
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  hall_id bigint not null references public.reserve_halls(id) on delete restrict,
  table_id bigint not null references public.reserve_tables(id) on delete restrict,
  reserved_date date not null,
  reserved_time time without time zone not null,
  duration_minutes smallint not null default 120 check (duration_minutes between 15 and 720),
  guests smallint not null default 2 check (guests between 1 and 300),
  guest_name text not null,
  phone text,
  menu_note text,
  note text,
  status text not null default 'booked' check (status in ('booked','occupied','completed','cancelled','no_show')),
  merged_tables text[] not null default array[]::text[],
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reservations_date_hall_idx
  on public.reservations (reserved_date, hall_id, reserved_time);
create index if not exists reservations_table_slot_idx
  on public.reservations (table_id, reserved_date, reserved_time);
create index if not exists reservations_active_status_idx
  on public.reservations (reserved_date, status)
  where status in ('booked','occupied');
create unique index if not exists reservations_legacy_identity_unique
  on public.reservations (hall_id, table_id, reserved_date, reserved_time, guest_name);

insert into public.reserve_halls (name, sort_order, note)
values
  ('Загальний зал', 1, 'Столи 7, 15, 16, 17, 18 не існують. Стіл 19 — круглий на 10 осіб.'),
  ('Камінний зал', 2, 'Столи 1–4, 6, 10 — на 8 осіб; 5, 7, 9 — на 4 особи.'),
  ('Нижній зал №2', 3, null),
  ('Нижній зал №3', 4, null),
  ('Літня тераса', 5, 'Столи 5.13–5.16 круглі й без накриття.'),
  ('Кабінки', 6, 'Усі кабінки розраховані на 6 осіб.')
on conflict (name) do update
set sort_order = excluded.sort_order,
    note = excluded.note,
    active = true;

with table_seed(hall_name, label, capacity, kind, x, y, sort_order) as (
  values
    ('Загальний зал','1',4,'small',0,6,1),('Загальний зал','2',4,'small',0,5,2),
    ('Загальний зал','3',4,'small',0,4,3),('Загальний зал','4',4,'small',0,3,4),
    ('Загальний зал','5',4,'small',0,2,5),('Загальний зал','6',4,'small',0,1,6),
    ('Загальний зал','8',4,'small',0,0,8),('Загальний зал','9',4,'small',0.8,0,9),
    ('Загальний зал','10',4,'small',1.6,0,10),('Загальний зал','11',4,'small',1.6,1,11),
    ('Загальний зал','12',4,'small',1.6,2,12),('Загальний зал','13',4,'small',1.6,3,13),
    ('Загальний зал','14',4,'small',1.6,4,14),('Загальний зал','19',10,'round-big',1.6,5,19),

    ('Камінний зал','1',8,'big-8',0,0,1),('Камінний зал','2',8,'big-8',1,0,2),
    ('Камінний зал','3',8,'big-8',2,0,3),('Камінний зал','4',8,'big-8',3,0,4),
    ('Камінний зал','5',4,'small',4,0,5),('Камінний зал','6',8,'big-8',0,1,6),
    ('Камінний зал','7',4,'small',1,1,7),('Камінний зал','9',4,'small',3,1,9),
    ('Камінний зал','10',8,'big-8',4,1,10),

    ('Нижній зал №2','1',6,'big',0,0,1),('Нижній зал №2','2',6,'big',0,1,2),
    ('Нижній зал №2','3',6,'big',0,2,3),('Нижній зал №2','4',4,'small',2,0,4),
    ('Нижній зал №2','5',4,'small',2,1,5),('Нижній зал №2','6',4,'small',2,2,6),

    ('Нижній зал №3','1',6,'big',2,0,1),('Нижній зал №3','2',6,'big',2,1,2),
    ('Нижній зал №3','3',6,'big',2,2,3),('Нижній зал №3','4',6,'big',2,3,4),
    ('Нижній зал №3','5',6,'big',0,0,5),('Нижній зал №3','6',4,'small',0,1,6),
    ('Нижній зал №3','7',6,'big',0,2,7),('Нижній зал №3','8',4,'small',0,3,8),
    ('Нижній зал №3','9',6,'big',0,4,9),

    ('Літня тераса','5.1',6,'big',0,0,1),('Літня тераса','5.2',4,'small',1,0,2),
    ('Літня тераса','5.3',6,'big',2,0,3),('Літня тераса','5.4',6,'big',3,0,4),
    ('Літня тераса','5.5',4,'small',4,0,5),('Літня тераса','5.6',6,'big',5,0,6),
    ('Літня тераса','5.7',4,'small',0,1,7),('Літня тераса','5.8',6,'big',1,1,8),
    ('Літня тераса','5.9',4,'small',2,1,9),('Літня тераса','5.10',6,'big',3,1,10),
    ('Літня тераса','5.11',4,'small',4,1,11),('Літня тераса','5.12',6,'big',5,1,12),
    ('Літня тераса','5.13',4,'round',0,2.45,13),('Літня тераса','5.14',4,'round',1,2.45,14),
    ('Літня тераса','5.15',4,'round',2,2.45,15),('Літня тераса','5.16',4,'round',3,2.45,16),

    ('Кабінки','8.5 VIP',6,'cabin',0,0,1),('Кабінки','8.4',6,'cabin',1.15,0,2),
    ('Кабінки','8.3',6,'cabin',2.3,0,3),('Кабінки','8.2',6,'cabin',3.45,0,4),
    ('Кабінки','8.1',6,'cabin',4.6,0,5)
)
insert into public.reserve_tables (
  hall_id, label, capacity, kind, position_x, position_y, sort_order
)
select h.id, s.label, s.capacity, s.kind, s.x, s.y, s.sort_order
from table_seed s
join public.reserve_halls h on h.name = s.hall_name
on conflict (hall_id, label) do update
set capacity = excluded.capacity,
    kind = excluded.kind,
    position_x = excluded.position_x,
    position_y = excluded.position_y,
    sort_order = excluded.sort_order,
    active = true;

with source as (
  select s.value::jsonb as bookings
  from public.settings s
  where s.key = 'tiflis_reserve_bookings'
), expanded as (
  select
    split_part(bucket.key, '::', 1) as hall_name,
    split_part(bucket.key, '::', 2) as table_label,
    booking.value as booking
  from source
  cross join lateral jsonb_each(source.bookings) as bucket(key, value)
  cross join lateral jsonb_array_elements(bucket.value) as booking(value)
), normalized as (
  select
    h.id as hall_id,
    t.id as table_id,
    (booking->>'date')::date as reserved_date,
    (booking->>'time')::time as reserved_time,
    greatest(1, least(300, coalesce(nullif(booking->>'guests','')::integer, 1)))::smallint as guests,
    left(coalesce(nullif(trim(booking->>'name'), ''), 'Без імені'), 180) as guest_name,
    nullif(left(trim(coalesce(booking->>'phone','')), 80), '') as phone,
    nullif(left(trim(coalesce(booking->>'menu','')), 1000), '') as menu_note,
    case when booking->>'status' in ('booked','occupied','completed','cancelled','no_show')
      then booking->>'status' else 'booked' end as status,
    case when jsonb_typeof(booking->'mergedWith') = 'array'
      then array(select jsonb_array_elements_text(booking->'mergedWith'))
      else array[]::text[] end as merged_tables,
    nullif(left(trim(coalesce(booking->>'createdBy','')), 120), '') as created_by,
    case
      when coalesce(booking->>'createdAt','') <> '' then (booking->>'createdAt')::timestamptz
      else now()
    end as created_at
  from expanded e
  join public.reserve_halls h on h.name = e.hall_name
  join public.reserve_tables t on t.hall_id = h.id and t.label = e.table_label
  where coalesce(booking->>'date','') ~ '^\d{4}-\d{2}-\d{2}$'
    and coalesce(booking->>'time','') ~ '^\d{2}:\d{2}$'
)
insert into public.reservations (
  hall_id, table_id, reserved_date, reserved_time, guests, guest_name,
  phone, menu_note, status, merged_tables, created_by, created_at
)
select
  hall_id, table_id, reserved_date, reserved_time, guests, guest_name,
  phone, menu_note, status, merged_tables, created_by, created_at
from normalized
on conflict (hall_id, table_id, reserved_date, reserved_time, guest_name) do nothing;

drop trigger if exists reserve_halls_set_updated_at on public.reserve_halls;
create trigger reserve_halls_set_updated_at
before update on public.reserve_halls
for each row execute function public.set_updated_at();

drop trigger if exists reserve_tables_set_updated_at on public.reserve_tables;
create trigger reserve_tables_set_updated_at
before update on public.reserve_tables
for each row execute function public.set_updated_at();

drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at
before update on public.reservations
for each row execute function public.set_updated_at();

commit;
